//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KevinJosueTarea_sistema_notas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class notas
    {
        public int id_notas { get; set; }
        public int id_estudiantes { get; set; }
        public int id_materia { get; set; }
        public string nota { get; set; }
    
        public virtual estudiantes estudiantes { get; set; }
        public virtual materias materias { get; set; }
    }
}
